<a href="https://colab.research.google.com/github/nora-mohamed25/data-analysis-portfolio/blob/main/Project_09_Car_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#CARS

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [ ]:
df = pd.read_csv('measurements.csv')

In [ ]:
df.head()

  distance consume  speed temp_inside  ...  rain sun refill liters  refill gas
0       28       5     26        21,5  ...     0   0            45         E10
1       12     4,2     30        21,5  ...     0   0           NaN         NaN
2     11,2     5,5     38        21,5  ...     0   0           NaN         NaN
3     12,9     3,9     36        21,5  ...     0   0           NaN         NaN
4     18,5     4,5     46        21,5  ...     0   0           NaN         NaN

[5 rows x 12 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   distance       388 non-null    object
 1   consume        388 non-null    object
 2   speed          388 non-null    int64
 3   temp_inside    376 non-null    object
 4   temp_outside   388 non-null    int64
 5   specials       93 non-null     object
 6   gas_type       388 non-null    object
 7   AC             388 non-null    int64
 8   rain           388 non-null    int64
 9   sun            388 non-null    int64
 10  refill liters  13 non-null     object
 11  refill gas     13 non-null     object
dtypes: int64(5), object(7)
memory usage: 36.5+ KB

In [ ]:

df["distance"] = df["distance"].str.replace(",", ".").astype(float)

In [ ]:

df["consume"] = df["consume"].str.replace(",", ".").astype(float)

In [ ]:

df["temp_inside"] = df["temp_inside"].str.replace(",", ".").astype(float)

In [ ]:
df.head()

   distance  consume  speed  temp_inside  ...  rain sun refill liters  refill gas
0      28.0      5.0     26         21.5  ...     0   0            45         E10
1      12.0      4.2     30         21.5  ...     0   0           NaN         NaN
2      11.2      5.5     38         21.5  ...     0   0           NaN         NaN
3      12.9      3.9     36         21.5  ...     0   0           NaN         NaN
4      18.5      4.5     46         21.5  ...     0   0           NaN         NaN

[5 rows x 12 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   distance       388 non-null    float64
 1   consume        388 non-null    float64
 2   speed          388 non-null    int64
 3   temp_inside    376 non-null    float64
 4   temp_outside   388 non-null    int64
 5   specials       93 non-null     object
 6   gas_type       388 non-null    object
 7   AC             388 non-null    int64
 8   rain           388 non-null    int64
 9   sun            388 non-null    int64
 10  refill liters  13 non-null     object
 11  refill gas     13 non-null     object
dtypes: float64(3), int64(5), object(4)
memory usage: 36.5+ KB

In [ ]:
df.isnull().sum()

distance           0
consume            0
speed              0
temp_inside       12
temp_outside       0
specials         295
gas_type           0
AC                 0
rain               0
sun                0
refill liters    375
refill gas       375
dtype: int64

In [ ]:
df.drop("specials", axis=1, inplace=True)
df.drop("refill liters", axis=1, inplace=True)
df.drop("refill gas", axis=1, inplace=True)

In [ ]:
df.tail()

     distance  consume  speed  temp_inside  ...  gas_type AC  rain  sun
383      16.0      3.7     39         24.5  ...      SP98  0     0    0
384      16.1      4.3     38         25.0  ...      SP98  1     0    0
385      16.0      3.8     45         25.0  ...      SP98  0     0    0
386      15.4      4.6     42         25.0  ...      SP98  1     0    0
387      14.7      5.0     25         25.0  ...      SP98  1     0    0

[5 rows x 9 columns]

In [ ]:
df.isnull().sum()

distance         0
consume          0
speed            0
temp_inside     12
temp_outside     0
gas_type         0
AC               0
rain             0
sun              0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   distance      388 non-null    float64
 1   consume       388 non-null    float64
 2   speed         388 non-null    int64
 3   temp_inside   376 non-null    float64
 4   temp_outside  388 non-null    int64
 5   gas_type      388 non-null    object
 6   AC            388 non-null    int64
 7   rain          388 non-null    int64
 8   sun           388 non-null    int64
dtypes: float64(3), int64(5), object(1)
memory usage: 27.4+ KB

In [ ]:
df["temp_inside"].fillna(df["temp_inside"].mean(), inplace=True)
df.isnull().sum()

/tmp/ipython-input-2772699747.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["temp_inside"].fillna(df["temp_inside"].mean(), inplace=True)

distance        0
consume         0
speed           0
temp_inside     0
temp_outside    0
gas_type        0
AC              0
rain            0
sun             0
dtype: int64

In [ ]:
df = pd.get_dummies(df, columns=["gas_type"])

In [ ]:
df.head()

   distance  consume  speed  ...  sun  gas_type_E10  gas_type_SP98
0      28.0      5.0     26  ...    0          True          False
1      12.0      4.2     30  ...    0          True          False
2      11.2      5.5     38  ...    0          True          False
3      12.9      3.9     36  ...    0          True          False
4      18.5      4.5     46  ...    0          True          False

[5 rows x 10 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   distance       388 non-null    float64
 1   consume        388 non-null    float64
 2   speed          388 non-null    int64
 3   temp_inside    388 non-null    float64
 4   temp_outside   388 non-null    int64
 5   AC             388 non-null    int64
 6   rain           388 non-null    int64
 7   sun            388 non-null    int64
 8   gas_type_E10   388 non-null    bool
 9   gas_type_SP98  388 non-null    bool
dtypes: bool(2), float64(3), int64(5)
memory usage: 25.1 KB

In [ ]:
x = df.drop("consume", axis=1)
y = df["consume"]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
linear_model = LinearRegression()
linear_model.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred = linear_model.predict(x_test)
y_pred

array([4.74692502, 5.1847064 , 5.10644769, 5.16651934, 4.51966168,
       6.11434363, 5.87388278, 5.14551183, 5.80315022, 4.87655267,
       4.07831353, 4.74302272, 6.58225847, 4.54029072, 5.06109287,
       5.17991161, 5.49238838, 5.06911829, 5.39049606, 5.24195546,
       4.3011057 , 5.28143951, 4.92514966, 5.15087136, 4.83345559,
       4.77906013, 4.37945698, 4.26392918, 5.06604612, 4.15092473,
       4.91424901, 5.20619029, 4.70539269, 4.56320904, 5.40745105,
       5.00264748, 4.64755769, 4.21550371, 5.06829308, 6.02452575,
       4.48460614, 5.23431947, 5.3186821 , 4.4451844 , 4.69734571,
       4.37839801, 5.01788276, 5.30337777, 4.90163157, 4.97085994,
       4.80328661, 5.34196069, 5.36656234, 5.19112467, 4.6497803 ,
       4.87790351, 6.7294414 , 5.28133594, 4.70082587, 4.74305518,
       5.40975734, 4.82900547, 4.53190327, 4.7490061 , 4.38484912,
       4.74235665, 5.47462918, 4.32618254, 4.97375382, 4.93732836,
       4.2804351 , 4.6799048 , 5.14468154, 4.90802982, 5.1062178 ,
       4.78293638, 5.26960682, 5.038259  ])

In [ ]:
df.compare = pd.DataFrame({"Actual": y_test, "Predicted": y_pred})
df.compare

     Actual  Predicted
271     5.6   4.746925
46      5.1   5.184706
167     6.1   5.106448
42      4.6   5.166519
349     4.3   4.519662
..      ...        ...
3       3.9   4.908030
18      4.9   5.106218
93      4.7   4.782936
108     4.7   5.269607
255     4.4   5.038259

[78 rows x 2 columns]

In [ ]:
mse = mean_squared_error(y_test, y_pred)
mse

0.8216359860810033